AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String

Globals:
  Function:
    Timeout: 300

Resources:
  GetEmbeddingFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 5120
      ImageUri: !Ref ImageUri
      AutoPublishAlias: TEST
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  Func:
    Description: Lambda name
    Value: !Ref GetEmbeddingFunc
  FuncVersion:
    Description: Lambda version
    Value: !Ref GetEmbeddingFunc.Version
  FuncAlias:
    Description: Lambda alias
    Value: !Ref GetEmbeddingFunc.Alias
